group: travis_latest
matrix:
  include:
    - language: python
      cache: pip
      python: 3.6
      before_script:
        - flake8 ../../ --count --select=E901,E999,F821,F822,F823 --show-source --statistics
        - flake8 ../../ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      allow_failures:
        - python: nightly
        - python: pypy3
      before_install:
        - cd .ci/python
      install:
        - pip install -r requirements.txt
    - language: node_js
      node_js: "12"
      before_install:
        - cd .ci/javascript
      install:
        - yarn
      script:
        - yarn run lint
    # - language: ruby
    #   rvm:
    #     - 2.5.0
    #   install:
    #     - gem install rubocop
    #   script:
    #     - rubocop
script:
  - true
notifications:
  on_failure: change
